spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          # native:
          # search-locations: "classpath:/config"
          search-locations: "file:///C:/Users/marina/Documents/config"

server:
  port: 8071

